/* ============================================================================
 * codegen.js — Generate openlcb_user_config.h and openlcb_user_config.c
 * ============================================================================ */

/* ── openlcb_user_config.h ── */

function generateUserConfigH() {
    var L = [];

    L.push('/* ===========================================================================');
    L.push(' * openlcb_user_config.h -- generated by Node Builder');
    L.push(' * OpenLcbCLib');
    L.push(' * Generated: ' + new Date().toISOString());
    L.push(' * =========================================================================== */');
    L.push('');
    L.push('#ifndef __OPENLCB_USER_CONFIG__');
    L.push('#define __OPENLCB_USER_CONFIG__');
    L.push('');

    /* Section 1: Feature Flags */
    section(L, '1', 'Feature Flags');
    addDefineIfChecked(L, 'flag-events',         'OPENLCB_COMPILE_EVENTS');
    addDefineIfChecked(L, 'flag-datagrams',      'OPENLCB_COMPILE_DATAGRAMS');
    addDefineIfChecked(L, 'flag-config-mem',     'OPENLCB_COMPILE_MEMORY_CONFIGURATION');
    addDefineIfChecked(L, 'flag-firmware',       'OPENLCB_COMPILE_FIRMWARE');
    addDefineIfChecked(L, 'flag-broadcast-time', 'OPENLCB_COMPILE_BROADCAST_TIME');
    addDefineIfChecked(L, 'flag-train',          'OPENLCB_COMPILE_TRAIN');
    addDefineIfChecked(L, 'flag-stream',         'OPENLCB_COMPILE_STREAM');
    L.push('');

    /* Section 2: Buffer Pool */
    section(L, '2', 'Core Message Buffer Pool');
    L.push('#define USER_DEFINED_BASIC_BUFFER_DEPTH              ' + getVal('buf-basic'));
    L.push('#define USER_DEFINED_DATAGRAM_BUFFER_DEPTH           ' + getVal('buf-datagram'));
    L.push('#define USER_DEFINED_SNIP_BUFFER_DEPTH               ' + getVal('buf-snip'));
    L.push('#define USER_DEFINED_STREAM_BUFFER_DEPTH             ' + getVal('buf-stream'));
    L.push('');

    /* Section 3: Virtual Node Allocation */
    section(L, '3', 'Virtual Node Allocation');
    L.push('#define USER_DEFINED_NODE_BUFFER_DEPTH               ' + getVal('buf-nodes'));
    L.push('');

    /* Section 4: Events */
    if (isChecked('flag-events')) {
        section(L, '4', 'Events (requires OPENLCB_COMPILE_EVENTS)');
        L.push('#define USER_DEFINED_PRODUCER_COUNT                  ' + getVal('evt-producers'));
        L.push('#define USER_DEFINED_PRODUCER_RANGE_COUNT            ' + getVal('evt-producer-ranges'));
        L.push('#define USER_DEFINED_CONSUMER_COUNT                  ' + getVal('evt-consumers'));
        L.push('#define USER_DEFINED_CONSUMER_RANGE_COUNT            ' + getVal('evt-consumer-ranges'));
        L.push('');
    }

    /* Section 5: Memory Configuration */
    section(L, '5', 'Memory Configuration');
    var cdiLen = (cdiBytes && cdiBytes.length > 0) ? cdiBytes.length : 1;
    L.push('#define USER_DEFINED_CDI_LENGTH                      ' + cdiLen);
    if (isChecked('flag-train')) {
        var fdiLen = (fdiBytes && fdiBytes.length > 0) ? fdiBytes.length : 1;
        L.push('#define USER_DEFINED_FDI_LENGTH                      ' + fdiLen);
    } else {
        L.push('#define USER_DEFINED_FDI_LENGTH                      100  /* placeholder */');
    }
    if (isChecked('flag-config-mem')) {
        L.push('#define USER_DEFINED_CONFIG_MEM_USER_NAME_ADDRESS    ' + getVal('cfg-user-name-addr'));
        L.push('#define USER_DEFINED_CONFIG_MEM_USER_DESCRIPTION_ADDRESS  ' + parseIntAuto(getVal('cfg-user-desc-addr')));
    } else {
        L.push('#define USER_DEFINED_CONFIG_MEM_USER_NAME_ADDRESS    0x00000000');
        L.push('#define USER_DEFINED_CONFIG_MEM_USER_DESCRIPTION_ADDRESS  62');
    }
    L.push('');

    /* Section 6: Train Protocol */
    if (isChecked('flag-train')) {
        section(L, '6', 'Train Protocol (requires OPENLCB_COMPILE_TRAIN)');
        L.push('#define USER_DEFINED_TRAIN_NODE_COUNT                ' + getVal('train-node-count'));
        L.push('#define USER_DEFINED_MAX_LISTENERS_PER_TRAIN         ' + getVal('train-listeners'));
        L.push('#define USER_DEFINED_MAX_TRAIN_FUNCTIONS             ' + getVal('train-functions'));
        L.push('');
    } else {
        section(L, '6', 'Train Protocol (disabled -- placeholders)');
        L.push('#define USER_DEFINED_TRAIN_NODE_COUNT                1');
        L.push('#define USER_DEFINED_MAX_LISTENERS_PER_TRAIN         1');
        L.push('#define USER_DEFINED_MAX_TRAIN_FUNCTIONS             1');
        L.push('');
    }

    L.push('#endif /* __OPENLCB_USER_CONFIG__ */');
    L.push('');

    return L.join('\n');
}

/* ── openlcb_user_config.c ── */

function generateUserConfigC() {
    var L = [];

    L.push('/* ===========================================================================');
    L.push(' * openlcb_user_config.c -- generated by Node Builder');
    L.push(' * OpenLcbCLib');
    L.push(' * Generated: ' + new Date().toISOString());
    L.push(' * =========================================================================== */');
    L.push('');
    L.push('#include "openlcb_user_config.h"');
    L.push('#include "src/openlcb/openlcb_types.h"');
    L.push('#include "src/openlcb/openlcb_defines.h"');
    L.push('');
    L.push('');
    L.push('const node_parameters_t OpenLcbUserConfig_node_parameters = {');
    L.push('');

    /* Auto-create counts */
    L.push('    .consumer_count_autocreate = 0,');
    L.push('    .producer_count_autocreate = 0,');
    L.push('');

    /* SNIP */
    L.push('    .snip.mfg_version = 4,');
    L.push('    .snip.name = "' + escapeC(getStrVal('snip-name')) + '",');
    L.push('    .snip.model = "' + escapeC(getStrVal('snip-model')) + '",');
    L.push('    .snip.hardware_version = "' + escapeC(getStrVal('snip-hw-version')) + '",');
    L.push('    .snip.software_version = "' + escapeC(getStrVal('snip-sw-version')) + '",');
    L.push('    .snip.user_version = 2,');
    L.push('');

    /* Protocol Support */
    var psi = buildProtocolSupportParts();
    L.push('    .protocol_support = (');
    for (var p = 0; p < psi.length; p++) {
        var sep = (p < psi.length - 1) ? ' |' : '';
        L.push('        ' + psi[p] + sep);
    }
    L.push('    ),');
    L.push('');

    /* Configuration Options */
    if (isChecked('flag-config-mem')) {
        L.push('    .configuration_options.high_address_space = CONFIG_MEM_SPACE_CONFIGURATION_DEFINITION_INFO,');
        L.push('    .configuration_options.low_address_space = ' + computeLowAddressSpaceDefine() + ',');
        L.push('    .configuration_options.read_from_manufacturer_space_0xfc_supported = true,');
        L.push('    .configuration_options.read_from_user_space_0xfb_supported = true,');
        L.push('    .configuration_options.stream_read_write_supported = ' + boolStr('cfgopt-stream-rw') + ',');
        L.push('    .configuration_options.unaligned_reads_supported = ' + boolStr('cfgopt-unaligned-reads') + ',');
        L.push('    .configuration_options.unaligned_writes_supported = ' + boolStr('cfgopt-unaligned-writes') + ',');
        L.push('    .configuration_options.write_to_user_space_0xfb_supported = true,');
        L.push('    .configuration_options.write_under_mask_supported = true,');
        L.push('    .configuration_options.description = "' + escapeC(getStrVal('cfgopt-desc')) + '",');
        L.push('');
    }

    /* Space 0xFF -- CDI */
    if (isChecked('flag-config-mem')) {
        L.push('    // Space 0xFF');
        L.push('    .address_space_configuration_definition.present = true,');
        L.push('    .address_space_configuration_definition.read_only = true,');
        L.push('    .address_space_configuration_definition.low_address_valid = false,');
        L.push('    .address_space_configuration_definition.low_address = 0,');
        var cdiHigh = (cdiBytes && cdiBytes.length > 0) ? (cdiBytes.length - 1) : 0;
        L.push('    .address_space_configuration_definition.highest_address = ' + cdiHigh + ',');
        L.push('    .address_space_configuration_definition.address_space = CONFIG_MEM_SPACE_CONFIGURATION_DEFINITION_INFO,');
        L.push('    .address_space_configuration_definition.description = "' + escapeC(getStrVal('addr-0xff-desc')) + '",');
        L.push('');
    }

    /* Space 0xFE -- All */
    if (isChecked('flag-config-mem')) {
        L.push('    // Space 0xFE');
        L.push('    .address_space_all.present = ' + boolStr('addr-0xfe-present') + ',');
        if (isChecked('addr-0xfe-present')) {
            L.push('    .address_space_all.read_only = ' + boolStr('addr-0xfe-readonly') + ',');
            L.push('    .address_space_all.low_address_valid = ' + boolStr('addr-0xfe-low-valid') + ',');
            if (isChecked('addr-0xfe-low-valid')) {
                L.push('    .address_space_all.low_address = ' + getVal('addr-0xfe-low') + ',');
            } else {
                L.push('    .address_space_all.low_address = 0,');
            }
            L.push('    .address_space_all.highest_address = ' + getVal('addr-0xfe-high') + ',');
        } else {
            L.push('    .address_space_all.read_only = true,');
            L.push('    .address_space_all.low_address_valid = false,');
            L.push('    .address_space_all.low_address = 0,');
            L.push('    .address_space_all.highest_address = 0xFFFF,');
        }
        L.push('    .address_space_all.address_space = CONFIG_MEM_SPACE_ALL,');
        L.push('    .address_space_all.description = "' + escapeC(getStrVal('addr-0xfe-desc')) + '",');
        L.push('');
    }

    /* Space 0xFD -- Configuration Memory */
    if (isChecked('flag-config-mem')) {
        L.push('    // Space 0xFD');
        L.push('    .address_space_config_memory.present = true,');
        L.push('    .address_space_config_memory.read_only = false,');
        var nameAddr = parseIntAuto(getVal('cfg-user-name-addr'));
        L.push('    .address_space_config_memory.low_address_valid = ' + (nameAddr !== 0 ? 'true' : 'false') + ',');
        L.push('    .address_space_config_memory.low_address = ' + (nameAddr !== 0 ? getVal('cfg-user-name-addr') : '0') + ',');
        L.push('    .address_space_config_memory.highest_address = ' + getVal('cfg-highest-addr') + ',');
        L.push('    .address_space_config_memory.address_space = CONFIG_MEM_SPACE_CONFIGURATION_MEMORY,');
        L.push('    .address_space_config_memory.description = "' + escapeC(getStrVal('addr-0xfd-desc')) + '",');
        L.push('');
    }

    /* Space 0xFC -- ACDI Manufacturer */
    if (isChecked('flag-config-mem')) {
        L.push('    // Space 0xFC');
        L.push('    .address_space_acdi_manufacturer.present = true,');
        L.push('    .address_space_acdi_manufacturer.read_only = true,');
        L.push('    .address_space_acdi_manufacturer.low_address_valid = false,');
        L.push('    .address_space_acdi_manufacturer.low_address = 0,');
        L.push('    .address_space_acdi_manufacturer.highest_address = 125 - 1,');
        L.push('    .address_space_acdi_manufacturer.address_space = CONFIG_MEM_SPACE_ACDI_MANUFACTURER_ACCESS,');
        L.push('    .address_space_acdi_manufacturer.description = "' + escapeC(getStrVal('addr-0xfc-desc')) + '",');
        L.push('');
    }

    /* Space 0xFB -- ACDI User */
    if (isChecked('flag-config-mem')) {
        L.push('    // Space 0xFB');
        L.push('    .address_space_acdi_user.present = true,');
        L.push('    .address_space_acdi_user.read_only = false,');
        L.push('    .address_space_acdi_user.low_address_valid = false,');
        L.push('    .address_space_acdi_user.low_address = 0,');
        L.push('    .address_space_acdi_user.highest_address = 128 - 1,');
        L.push('    .address_space_acdi_user.address_space = CONFIG_MEM_SPACE_ACDI_USER_ACCESS,');
        L.push('    .address_space_acdi_user.description = "' + escapeC(getStrVal('addr-0xfb-desc')) + '",');
        L.push('');
    }

    /* Space 0xFA -- Train FDI */
    if (isChecked('flag-train')) {
        L.push('    // Space 0xFA');
        L.push('    .address_space_train_function_definition_info.present = true,');
        L.push('    .address_space_train_function_definition_info.read_only = true,');
        L.push('    .address_space_train_function_definition_info.low_address_valid = false,');
        L.push('    .address_space_train_function_definition_info.low_address = 0,');
        var fdiHigh = (fdiBytes && fdiBytes.length > 0) ? (fdiBytes.length - 1) : 0;
        L.push('    .address_space_train_function_definition_info.highest_address = ' + fdiHigh + ',');
        L.push('    .address_space_train_function_definition_info.address_space = CONFIG_MEM_SPACE_TRAIN_FUNCTION_DEFINITION_INFO,');
        L.push('    .address_space_train_function_definition_info.description = "' + escapeC(getStrVal('addr-0xfa-desc')) + '",');
        L.push('');

        /* Space 0xF9 -- Train Function Config */
        L.push('    // Space 0xF9');
        L.push('    .address_space_train_function_config_memory.present = true,');
        L.push('    .address_space_train_function_config_memory.read_only = false,');
        L.push('    .address_space_train_function_config_memory.low_address_valid = false,');
        L.push('    .address_space_train_function_config_memory.low_address = 0,');
        L.push('    .address_space_train_function_config_memory.highest_address = ' + getVal('addr-0xf9-high') + ',');
        L.push('    .address_space_train_function_config_memory.address_space = CONFIG_MEM_SPACE_TRAIN_FUNCTION_CONFIGURATION_MEMORY,');
        L.push('    .address_space_train_function_config_memory.description = "' + escapeC(getStrVal('addr-0xf9-desc')) + '",');
        L.push('');
    }

    /* Space 0xEF -- Firmware */
    if (isChecked('flag-firmware')) {
        L.push('    // Space 0xEF');
        L.push('    .address_space_firmware.present = true,');
        L.push('    .address_space_firmware.read_only = false,');
        L.push('    .address_space_firmware.low_address_valid = false,');
        L.push('    .address_space_firmware.low_address = 0,');
        L.push('    .address_space_firmware.highest_address = 0xFFFFFFFF,');
        L.push('    .address_space_firmware.address_space = CONFIG_MEM_SPACE_FIRMWARE,');
        L.push('    .address_space_firmware.description = "' + escapeC(getStrVal('addr-0xef-desc')) + '",');
        L.push('');
    }

    /* CDI byte array */
    L.push('    .cdi = {');
    if (cdiBytes && cdiBytes.length > 0) {
        L.push(formatByteArrayAsC(cdiBytes));
    } else {
        L.push('        0x00');
    }
    L.push('    },');
    L.push('');

    /* FDI byte array */
    if (isChecked('flag-train')) {
        L.push('    .fdi = {');
        if (fdiBytes && fdiBytes.length > 0) {
            L.push(formatByteArrayAsC(fdiBytes));
        } else {
            L.push('        0x00');
        }
        L.push('    },');
        L.push('');
    }

    L.push('};');
    L.push('');

    return L.join('\n');
}

/* Compute lowest active address space as a #define name */
function computeLowAddressSpaceDefine() {

    if (isChecked('flag-firmware'))   return 'CONFIG_MEM_SPACE_FIRMWARE';
    if (isChecked('flag-train'))      return 'CONFIG_MEM_SPACE_TRAIN_FUNCTION_CONFIGURATION_MEMORY';
    if (isChecked('flag-config-mem')) return 'CONFIG_MEM_SPACE_ACDI_USER_ACCESS';
    return 'CONFIG_MEM_SPACE_ACDI_MANUFACTURER_ACCESS';
}

/* helper to emit a section banner */
function section(L, num, title) {
    L.push('/* ===========================================================================');
    L.push(' * Section ' + num + ': ' + title);
    L.push(' * =========================================================================== */');
    L.push('');
}
