var searchData=
[
  ['id_0',['id',['../structopenlcb__node___t_a_g.html#a7e290573ef1be67b92a2c745e3b00d1d',1,'openlcb_node_TAG']]],
  ['identifier_1',['identifier',['../structcan__msg__struct.html#a69cce241723713fbb29eec527865ce3b',1,'can_msg_struct']]],
  ['identifier_20field_20masks_2',['CAN Identifier Field Masks',['../group__can__identifier__masks.html',1,'']]],
  ['identifiers_3',['CAN Control Frame Identifiers',['../group__can__control__frames.html',1,'']]],
  ['ids_4',['IDs',['../group__broadcast__time__events.html',1,'Broadcast Time Protocol Event IDs'],['../group__well__known__events.html',1,'Well-Known Event IDs']]],
  ['important_20read_20before_20use_5',['SCOPE — IMPORTANT, READ BEFORE USE',['../internal__node__alias__table_8h.html#autotoc_md0',1,'']]],
  ['incoming_5fmsg_5finfo_6',['incoming_msg_info',['../structopenlcb__statemachine__info__t.html#ac344e1481aeef01899a189f5a6469f39',1,'openlcb_statemachine_info_t']]],
  ['index_7',['index',['../structopenlcb__node___t_a_g.html#aae5a12e607d0f782506d9e6ec6179c64',1,'openlcb_node_TAG']]],
  ['indicator_20bits_8',['Protocol Support Indicator Bits',['../group__protocol__support__bits.html',1,'']]],
  ['information_20flags_9',['Address Space Information Flags',['../group__address__space__info__flags.html',1,'']]],
  ['information_20protocol_20mti_20codes_10',['Simple Node Information Protocol MTI Codes',['../group__mti__snip.html',1,'']]],
  ['initialized_11',['initialized',['../structopenlcb__node__state__t.html#aedeffc7d23da25d52b9a50045189fe2b',1,'openlcb_node_state_t']]],
  ['inprocess_12',['inprocess',['../structopenlcb__msg__state__t.html#a6db0c09032acfed6152272e0851576e0',1,'openlcb_msg_state_t']]],
  ['interface_5fcan_5flogin_5fmessage_5fhandler_5ft_13',['interface_can_login_message_handler_t',['../structinterface__can__login__message__handler__t.html',1,'']]],
  ['interface_5fcan_5flogin_5fstate_5fmachine_5ft_14',['interface_can_login_state_machine_t',['../structinterface__can__login__state__machine__t.html',1,'']]],
  ['interface_5fcan_5fmain_5fstatemachine_5ft_15',['interface_can_main_statemachine_t',['../structinterface__can__main__statemachine__t.html',1,'']]],
  ['interface_5fcan_5frx_5fmessage_5fhandler_5ft_16',['interface_can_rx_message_handler_t',['../structinterface__can__rx__message__handler__t.html',1,'']]],
  ['interface_5fcan_5frx_5fstatemachine_5ft_17',['interface_can_rx_statemachine_t',['../structinterface__can__rx__statemachine__t.html',1,'']]],
  ['interface_5fcan_5ftx_5fmessage_5fhandler_5ft_18',['interface_can_tx_message_handler_t',['../structinterface__can__tx__message__handler__t.html',1,'']]],
  ['interface_5fcan_5ftx_5fstatemachine_5ft_19',['interface_can_tx_statemachine_t',['../structinterface__can__tx__statemachine__t.html',1,'']]],
  ['interface_5fopenlcb_5fapplication_5fbroadcast_5ftime_5ft_20',['interface_openlcb_application_broadcast_time_t',['../structinterface__openlcb__application__broadcast__time__t.html',1,'']]],
  ['interface_5fopenlcb_5fapplication_5ft_21',['interface_openlcb_application_t',['../structinterface__openlcb__application__t.html',1,'']]],
  ['interface_5fopenlcb_5fapplication_5ftrain_5ft_22',['interface_openlcb_application_train_t',['../structinterface__openlcb__application__train__t.html',1,'']]],
  ['interface_5fopenlcb_5flogin_5fmessage_5fhandler_5ft_23',['interface_openlcb_login_message_handler_t',['../structinterface__openlcb__login__message__handler__t.html',1,'']]],
  ['interface_5fopenlcb_5flogin_5fstate_5fmachine_5ft_24',['interface_openlcb_login_state_machine_t',['../structinterface__openlcb__login__state__machine__t.html',1,'']]],
  ['interface_5fopenlcb_5fmain_5fstatemachine_5ft_25',['interface_openlcb_main_statemachine_t',['../structinterface__openlcb__main__statemachine__t.html',1,'']]],
  ['interface_5fopenlcb_5fnode_5ft_26',['interface_openlcb_node_t',['../structinterface__openlcb__node__t.html',1,'']]],
  ['interface_5fopenlcb_5fprotocol_5fbroadcast_5ftime_5fhandler_5ft_27',['interface_openlcb_protocol_broadcast_time_handler_t',['../structinterface__openlcb__protocol__broadcast__time__handler__t.html',1,'']]],
  ['interface_5fopenlcb_5fprotocol_5fevent_5ftransport_5ft_28',['interface_openlcb_protocol_event_transport_t',['../structinterface__openlcb__protocol__event__transport__t.html',1,'']]],
  ['interface_5fopenlcb_5fprotocol_5fmessage_5fnetwork_5ft_29',['interface_openlcb_protocol_message_network_t',['../structinterface__openlcb__protocol__message__network__t.html',1,'']]],
  ['interface_5fopenlcb_5fprotocol_5fsnip_5ft_30',['interface_openlcb_protocol_snip_t',['../structinterface__openlcb__protocol__snip__t.html',1,'']]],
  ['interface_5fprotocol_5fconfig_5fmem_5foperations_5fhandler_5ft_31',['interface_protocol_config_mem_operations_handler_t',['../structinterface__protocol__config__mem__operations__handler__t.html',1,'']]],
  ['interface_5fprotocol_5fconfig_5fmem_5fread_5fhandler_5ft_32',['interface_protocol_config_mem_read_handler_t',['../structinterface__protocol__config__mem__read__handler__t.html',1,'']]],
  ['interface_5fprotocol_5fconfig_5fmem_5fwrite_5fhandler_5ft_33',['interface_protocol_config_mem_write_handler_t',['../structinterface__protocol__config__mem__write__handler__t.html',1,'']]],
  ['interface_5fprotocol_5fdatagram_5fhandler_5ft_34',['interface_protocol_datagram_handler_t',['../structinterface__protocol__datagram__handler__t.html',1,'']]],
  ['interface_5fprotocol_5ftrain_5fhandler_5ft_35',['interface_protocol_train_handler_t',['../structinterface__protocol__train__handler__t.html',1,'']]],
  ['interface_5fprotocol_5ftrain_5fsearch_5fhandler_5ft_36',['interface_protocol_train_search_handler_t',['../structinterface__protocol__train__search__handler__t.html',1,'']]],
  ['interface_5ftcp_5flink_5fcontrol_5ft_37',['interface_tcp_link_control_t',['../structinterface__tcp__link__control__t.html',1,'']]],
  ['interface_5ftcp_5flogin_5fstatemachine_5ft_38',['interface_tcp_login_statemachine_t',['../structinterface__tcp__login__statemachine__t.html',1,'']]],
  ['interface_5ftcp_5fmain_5fstatemachine_5ft_39',['interface_tcp_main_statemachine_t',['../structinterface__tcp__main__statemachine__t.html',1,'']]],
  ['interface_5ftcp_5frx_5fstatemachine_5ft_40',['interface_tcp_rx_statemachine_t',['../structinterface__tcp__rx__statemachine__t.html',1,'']]],
  ['interface_5ftcp_5ftx_5fstatemachine_5ft_41',['interface_tcp_tx_statemachine_t',['../structinterface__tcp__tx__statemachine__t.html',1,'']]],
  ['internal_5fnode_5falias_5ftable_2ec_42',['internal_node_alias_table.c',['../internal__node__alias__table_8c.html',1,'']]],
  ['internal_5fnode_5falias_5ftable_2eh_43',['internal_node_alias_table.h',['../internal__node__alias__table_8h.html',1,'']]],
  ['internalnodealiastable_5fclear_5fhas_5fduplicate_5falias_5fflag_44',['InternalNodeAliasTable_clear_has_duplicate_alias_flag',['../internal__node__alias__table_8c.html#a6024bad1cb15c6e63bba24e2f4cf5a18',1,'InternalNodeAliasTable_clear_has_duplicate_alias_flag(void):&#160;internal_node_alias_table.c'],['../internal__node__alias__table_8h.html#a6024bad1cb15c6e63bba24e2f4cf5a18',1,'InternalNodeAliasTable_clear_has_duplicate_alias_flag(void):&#160;internal_node_alias_table.c']]],
  ['internalnodealiastable_5ffind_5fmapping_5fby_5falias_45',['InternalNodeAliasTable_find_mapping_by_alias',['../internal__node__alias__table_8c.html#a8bdb26010b5c951e0572e156c96339e6',1,'InternalNodeAliasTable_find_mapping_by_alias(uint16_t alias):&#160;internal_node_alias_table.c'],['../internal__node__alias__table_8h.html#a8bdb26010b5c951e0572e156c96339e6',1,'InternalNodeAliasTable_find_mapping_by_alias(uint16_t alias):&#160;internal_node_alias_table.c']]],
  ['internalnodealiastable_5ffind_5fmapping_5fby_5fnode_5fid_46',['InternalNodeAliasTable_find_mapping_by_node_id',['../internal__node__alias__table_8c.html#a47852d92695fce67736e7cde5e333fca',1,'InternalNodeAliasTable_find_mapping_by_node_id(node_id_t node_id):&#160;internal_node_alias_table.c'],['../internal__node__alias__table_8h.html#a47852d92695fce67736e7cde5e333fca',1,'InternalNodeAliasTable_find_mapping_by_node_id(node_id_t node_id):&#160;internal_node_alias_table.c']]],
  ['internalnodealiastable_5fflush_47',['InternalNodeAliasTable_flush',['../internal__node__alias__table_8c.html#aba23f329b8d7112ada222f9feaf1bb19',1,'InternalNodeAliasTable_flush(void):&#160;internal_node_alias_table.c'],['../internal__node__alias__table_8h.html#aba23f329b8d7112ada222f9feaf1bb19',1,'InternalNodeAliasTable_flush(void):&#160;internal_node_alias_table.c']]],
  ['internalnodealiastable_5fget_5falias_5fmapping_5finfo_48',['InternalNodeAliasTable_get_alias_mapping_info',['../internal__node__alias__table_8c.html#a4cd9a10ebd01f0ef35c0aa956dd71701',1,'InternalNodeAliasTable_get_alias_mapping_info(void):&#160;internal_node_alias_table.c'],['../internal__node__alias__table_8h.html#a4cd9a10ebd01f0ef35c0aa956dd71701',1,'InternalNodeAliasTable_get_alias_mapping_info(void):&#160;internal_node_alias_table.c']]],
  ['internalnodealiastable_5finitialize_49',['InternalNodeAliasTable_initialize',['../internal__node__alias__table_8c.html#a708a91c6693ca1fb7ede1f9cfc96f46d',1,'InternalNodeAliasTable_initialize(void):&#160;internal_node_alias_table.c'],['../internal__node__alias__table_8h.html#a708a91c6693ca1fb7ede1f9cfc96f46d',1,'InternalNodeAliasTable_initialize(void):&#160;internal_node_alias_table.c']]],
  ['internalnodealiastable_5fregister_50',['InternalNodeAliasTable_register',['../internal__node__alias__table_8c.html#a43c158f11c244b0c50e099a8d90569a9',1,'InternalNodeAliasTable_register(uint16_t alias, node_id_t node_id):&#160;internal_node_alias_table.c'],['../internal__node__alias__table_8h.html#a43c158f11c244b0c50e099a8d90569a9',1,'InternalNodeAliasTable_register(uint16_t alias, node_id_t node_id):&#160;internal_node_alias_table.c']]],
  ['internalnodealiastable_5fset_5fhas_5fduplicate_5falias_5fflag_51',['InternalNodeAliasTable_set_has_duplicate_alias_flag',['../internal__node__alias__table_8c.html#affff5cd83e49ca2a17ad66942dc0c199',1,'InternalNodeAliasTable_set_has_duplicate_alias_flag(void):&#160;internal_node_alias_table.c'],['../internal__node__alias__table_8h.html#affff5cd83e49ca2a17ad66942dc0c199',1,'InternalNodeAliasTable_set_has_duplicate_alias_flag(void):&#160;internal_node_alias_table.c']]],
  ['internalnodealiastable_5funregister_52',['InternalNodeAliasTable_unregister',['../internal__node__alias__table_8c.html#adcbac9366d5889c2665bcc733b3d0dcf',1,'InternalNodeAliasTable_unregister(uint16_t alias):&#160;internal_node_alias_table.c'],['../internal__node__alias__table_8h.html#adcbac9366d5889c2665bcc733b3d0dcf',1,'InternalNodeAliasTable_unregister(uint16_t alias):&#160;internal_node_alias_table.c']]],
  ['invalid_53',['invalid',['../structopenlcb__msg__state__t.html#a287d7f5cafc29863a809d81fc80d55b3',1,'openlcb_msg_state_t']]],
  ['is_5fallocated_54',['is_allocated',['../structbroadcast__clock__t.html#a46e75766403b17e73e356109aee081c7',1,'broadcast_clock_t']]],
  ['is_5fconsumer_55',['is_consumer',['../structbroadcast__clock__t.html#a5d71a55f741db3daa42ad443b6a0c4fd',1,'broadcast_clock_t']]],
  ['is_5fduplicate_56',['is_duplicate',['../structalias__mapping__struct.html#a70cebb5663459ea9444b61f00f1e3998',1,'alias_mapping_struct']]],
  ['is_5flong_5faddress_57',['is_long_address',['../structtrain__state___t_a_g.html#a9231569054cae5f2bd081aaf0978b75e',1,'train_state_TAG']]],
  ['is_5fpermitted_58',['is_permitted',['../structalias__mapping__struct.html#a1c19fd4ba1ee0bc1f0d7def30ede49a2',1,'alias_mapping_struct']]],
  ['is_5fproducer_59',['is_producer',['../structbroadcast__clock__t.html#ad6dd46df120573b4540c49bfc3e67895',1,'broadcast_clock_t']]],
  ['is_5frunning_60',['is_running',['../structbroadcast__clock__state__t.html#a95cbd6b99430748422cc048b4f29dc52',1,'broadcast_clock_state_t']]],
  ['is_5ftx_5fbuffer_5fclear_61',['is_tx_buffer_clear',['../structcan__config__t.html#a600ed23c9d8e12fbcbb70a922e21be15',1,'can_config_t::is_tx_buffer_clear'],['../structtcp__config__t.html#a600ed23c9d8e12fbcbb70a922e21be15',1,'tcp_config_t::is_tx_buffer_clear'],['../structinterface__tcp__tx__statemachine__t.html#a600ed23c9d8e12fbcbb70a922e21be15',1,'interface_tcp_tx_statemachine_t::is_tx_buffer_clear']]],
  ['is_5ftx_5fbuffer_5fempty_62',['is_tx_buffer_empty',['../structinterface__can__tx__statemachine__t.html#a2e9d4e2d961ae1797f5a9877b4771b15',1,'interface_can_tx_statemachine_t']]]
];
