; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 921600

build_flags = -std=gnu99

board_build.partitions = ../../shared/partitions.csv

build_src_filter = -<**>
                   +<*.c>
                   +<*.cpp>
                   +<*.h>
                   +<openlcb_c_lib_bootloader/crc/*.c>
                   +<openlcb_c_lib_bootloader/crc/*.h>
                   +<openlcb_c_lib_bootloader/drivers/canbus/*.c>
                   +<openlcb_c_lib_bootloader/drivers/canbus/*.h>
                   +<openlcb_c_lib_bootloader/openlcb/*.c>
                   +<openlcb_c_lib_bootloader/openlcb/*.h>
                   +<application_drivers/*.c>
                   +<application_drivers/*.cpp>
                   +<../../shared/*.c>
                   +<../../shared/*.h>
